##Definition for general roles
aws_core_roles:
  Developer:
    managed_policies_arn:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
      - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
      - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
      - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
      - arn:aws:iam::{{AWS_ACCOUNT}}:policy/AccountManagement
      - arn:aws:iam::{{AWS_ACCOUNT}}:policy/AccountColor
      - arn:aws:iam::{{AWS_ACCOUNT}}:policy/CostExplorer
    #   - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
    #   - arn:aws:iam::aws:policy/IAMFullAccess
    assume_role_policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            AWS:
              - arn:aws:iam::{{AWS_ACCOUNT}}:root
              #- arn:aws:iam::{{AWS_ACCOUNT}}:role/Developer
          Action:
            - sts:AssumeRole
            
infra_managed_policies:
  AccountManagement:
    policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - account:GetRegionOptStatus
            - account:GetPrimaryEmail
            - account:GetContactInformation
            - account:GetAccountInformation
            - account:GetGovCloudAccountInformation
            - account:GetAlternateContact
          Resource:
            - "*"
  AccountColor:
    policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - "uxc:ListServices"
            - "uxc:GetAccountColor"
            - "uxc:GetAccountCustomizations"
          Resource:
            - "*"
  CostExplorer:
    policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - "ce:GetCostAndUsage"
            - "ce:GetReservationPurchaseRecommendation"
            - "ce:GetPreferences"
            - "ce:ListTagsForResource"
            - "ce:GetReservationUtilization"
            - "ce:GetCostAndUsageComparisons"
            - "ce:GetCostCategories"
            - "ce:GetSavingsPlansPurchaseRecommendation"
            - "ce:GetSavingsPlansUtilizationDetails"
            - "ce:GetDimensionValues"
            - "ce:GetAnomalySubscriptions"
            - "ce:DescribeReport"
            - "ce:GetReservationCoverage"
            - "ce:GetCommitmentPurchaseAnalysis"
            - "ce:GetAnomalyMonitors"
            - "ce:GetUsageForecast"
            - "ce:DescribeNotificationSubscription"
            - "ce:DescribeCostCategoryDefinition"
            - "ce:GetRightsizingRecommendation"
            - "ce:GetSavingsPlansUtilization"
            - "ce:GetAnomalies"
            - "ce:GetCostForecast"
            - "ce:GetApproximateUsageRecords"
            - "ce:GetCostAndUsageWithResources"
            - "ce:GetSavingsPlanPurchaseRecommendationDetails"
            - "ce:GetCostComparisonDrivers"
            - "ce:GetSavingsPlansCoverage"
            - "ce:GetConsoleActionSetEnforced"
            - "ce:GetTags"
          Resource:
            - "*"


aws_core_users:
  Developer:
    managed_policies_arn:
    managed_policies_definitions:
      AssumeRolePolicy:
        policy:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource:
                - "*"