version: '3.1'
services:
   terragrunt:
    image: alpine/terragrunt:1.6.6
    volumes:
      - ./deployment:/dev/terragrunt
    command: ["bash"]
  

 #aws eks update-kubeconfig --region us-west-2 --name dev_infra_cluster 

#These no need to remove them
# Units Installation Order

# Base - Core - Iam
# Base - Core - route53
#   - Destroy

# Deployments - Core - Main
#    - Destroy
# Deployments - Core - Kubernetes - Installation
#    - Destroy
# Deployments - Core - Kubernetes - Setup
#    - Destroy

#terragrunt run --all plan  --filter 'base/dev/global/core/route53/' -out-dir tfplan
#terragrunt run --all apply  --filter 'base/dev/global/core/route53/' -out-dir tfplan
#terragrunt run --all destroy  --filter 'base/dev/global/core/route53/'


 # terragrunt run --all plan  --filter 'deployments/dev/us-west-2/core/main/' -out-dir tfplan
#terragrunt run --all apply  --filter 'deployments/dev/us-west-2/core/main/' -out-dir tfplan
#terragrunt run --all destroy  --filter 'deployments/dev/us-west-2/core/main/'

 # terragrunt run --all plan  --filter 'deployments/dev/us-west-2/core/kubernetes/**' -out-dir tfplan
#terragrunt run --all apply  --filter 'deployments/dev/us-west-2/core/kubernetes/**' -out-dir tfplan
#terragrunt run --all destroy  --filter 'deployments/dev/us-west-2/core/kubernetes/**'

 # terragrunt run --all plan  --filter 'deployments/dev/us-west-2/core/kubernetes/**' -out-dir tfplan
#terragrunt run --all apply  --filter 'deployments/dev/us-west-2/core/kubernetes/' -out-dir tfplan

#docker run -ti --rm -v $HOME/.aws:/root/.aws -v ${HOME}/.ssh:/root/.ssh -v .:/apps alpine/terragrunt:1.7.4 bash
#terragrunt run-all show -json plan > plan.json

#terragrunt init  -reconfigure  --filter deployments/dev/us-west-2/core/main/
#terragrunt init  -upgrade  --filter deployments/dev/us-west-2/core/main/

#cd base/dev/global/core && terragrunt backend bootstrap  --all && cd ~/terragrunt-infra/infra-code
#cd deployment/dev/us-west-2/core/main/ && terragrunt backend bootstrap --all &&  cd ~/terragrunt-infra/infra-code
#terragrunt backend delete --all  --non-interactive


#terragrunt run --all plan --filter 'base/dev/global/core/**' -out-dir=tfplan
#terragrunt run --all apply --filter 'base/dev/global/core/**' --parallelism=4  -out-dir=tfplan


#terragrunt run --all plan --filter 'deployments/dev/us-west-2/core/main/' -out-dir=tfplan
#terragrunt run --all apply --filter 'deployments/dev/us-west-2/core/main/' --parallelism=4  -out-dir=tfplan

#terragrunt run --all plan --filter 'deployments/dev/us-west-2/core/kubernetes/' -out-dir=tfplan
#terragrunt run --all apply --filter 'deployments/dev/us-west-2/core/kubernetes/' --parallelism=4  -out-dir=tfplan

#terragrunt run --all plan --filter 'deployments/dev/us-west-2/core/prom-grafana-stack/' -out-dir=tfplan
#terragrunt run --all apply --filter 'deployments/dev/us-west-2/core/prom-grafana-stack/' --parallelism=4  -out-dir=tfplan

#terragrunt run --all destroy  --filter 'deployments/dev/us-west-2/core/prom-grafana-stack/'
#terragrunt run --all destroy  --filter 'deployments/dev/us-west-2/core/kubernetes/'
#terragrunt run --all destroy  --filter 'deployments/dev/us-west-2/core/main/'

#terragrunt run --all output --filter 'base/dev/global/core/**' 
#terragrunt state list --all  --filter 'base/dev/global/core/**' 
#terragrunt state pull --all  --filter 'base/dev/global/core/**'  > local_copy.tfstate 

#terragrunt run-all output --terragrunt-non-interactive --terragrunt-working-dir infra-code/deployment/dev/us-west-2/core/kubernetes
#terragrunt run-all init --terragrunt-non-interactive --terragrunt-working-dir infra-code/deployment/dev/us-west-2/core/ --terragrunt-log-level debug --terragrunt-debug

#terragrunt run-all init -migrate-state --terragrunt-working-dir infra-code/deployment/dev/us-west-2/core/
#terragrunt run-all state list  --terragrunt-non-interactive --terragrunt-working-dir infra-code/deployment/dev/us-west-2/core
#terragrunt run-all state list  --terragrunt-non-interactive --terragrunt-working-dir infra-code/deployment/dev/us-west-2/core/kubernetes
#terragrunt run-all state list  --terragrunt-non-interactive --terragrunt-working-dir infra-code/deployment/dev/us-west-2/projects/raffle
#To remove a lock go to dynamo table and remove the item with info column

#aws sts assume-role --role-arn "arn:aws:iam::324711057459:role/Developer" --role-session-name AWSCLI-Session  --duration-seconds 43200
#aws sts assume-role --role-arn "arn:aws:iam::324711057459:role/Developer" --role-session-name Developer_Session --profile AdminSSO
#aws sts get-caller-identity

#aws eks update-kubeconfig --region us-west-2 --name dev_infra_cluster 
#kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
#kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.4.2/components.yaml

#kubectl -n dev-prom-grafana-stack  port-forward svc/kube-prometheus-stack-grafana 3000:80 &

#ps -ef | grep port-forward
#kubectl proxy


### ACCESS TO KUBERNETES DASHBOARD
#kubectl -n dev-kubernetes-dashboard  port-forward svc/dev-kubernetes-dashboard-kong-proxy 8443:443 &
#kubectl -n dev-kube-monitoring create token dev-kube-dashboard-admin --duration=45000s

#ACCESS TO HEADLAMP DASHBOARD
#kubectl port-forward -n dev-kube-monitoring deployment/dev-headlamp 8080:4466 &
#kubectl -n dev-kube-monitoring create token dev-headlamp-admin --duration=45000s
#

#terragrunt run-all state rm module.module_kubernetes.aws_eks_cluster.eks_cluster --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes
#terragrunt run-all state rm module.module_core_setup_kubernetes.data.aws_eks_cluster_auth.aws_eks_cluster --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes
#terragrunt run-all state rm module.module_core_setup_kubernetes.helm_release.ingress-nginx --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes
#terragrunt run-all state rm module.module_core_setup_kubernetes.helm_release.kubernetes-dashboard --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes
#terragrunt run-all state rm module.module_core_setup_kubernetes.kubernetes_namespace.namespaces[\"networking\"] --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes 
#terragrunt run-all state rm module.module_kubernetes.data.aws_iam_role.kube_iam_sec_role --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes
#terragrunt run-all state rm module.module_kubernetes.data.aws_security_group.kube_sec_groups[\"eks_cluster_sec_group\"] --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes 
#terragrunt run-all state rm module.module_kubernetes.aws_cloudwatch_log_group.kube_cluster_cloudwatch_logs --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes 
#terragrunt run-all state rm module.module_kubernetes.aws_eks_cluster.eks_cluster --terragrunt-non-interactive --terragrunt-working-dir deployment/dev/us-west-2/core/kubernetes

#curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#unzip awscliv2.zip
#sudo ./aws/install


 #terragrunt run  state rm kubernetes_namespace_v1.namespaces[\"kube-monitoring\"] --filter 'deployments/dev/us-west-2/core/kubernetes/setup'