enable_attach_environment_to_namespace: true

#The namespace name format is <environment>-<namespace_name> to avoid conflicts with other environments. 
#The same applies to service accounts and cluster roles.
kube_namespaces:
  - namespace
  - kubernetes-dashboard
  - networking
  - prom-grafana-stack
  - headlamp

kube_node_groups:
  - {} #empty object means 1 node with default configs defined in defaults.yml

kube_infra_service_accounts:
  admin-sac:
    namespaces:
      - namespace
  external-dns:
    namespaces:
      - networking
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::{ACCOUNT_ID}:role/ExternalDnsServiceAccountRole

kube_cluster_roles:
  external-dns:
    rules:
      - apiGroups: [""]
        resources: ["services", "endpoints", "pods"]
        verbs: ["get", "watch", "list"]
      - apiGroups: ["extensions", "networking.k8s.io"]
        resources: ["ingresses"]
        verbs: ["get", "watch", "list"]
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["watch", "list"]
      - apiGroups: ["discovery.k8s.io"]
        resources: ["endpointslices"]
        verbs: ["get", "watch", "list"]

kube_role_bindings:
  - kind: ServiceAccount
    name: admin-sac
    namespace: namespace
    bindings:
      - api_group: rbac.authorization.k8s.io
        kind: ClusterRole
        name: "@cluster-admin"

  - kind: ServiceAccount
    name: external-dns
    namespace: networking
    bindings:
      - api_group: rbac.authorization.k8s.io
        kind: ClusterRole
        name: external-dns

#CLUSTER AUTHENTICATION CONFIG
cluster_principals_authentication_config:
  authentication_admin_role_arns:
    root_user:
      principal_arn: arn:aws:iam::324711057459:root
      kubernetes_groups: ["cluster-admin"]
      type: STANDARD
  authentication_access_policy_associations:
    root_user_eks_cluster_admin_policy_association:
      principal_arn: arn:aws:iam::324711057459:root
      policy_arn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      type: cluster
