app_roles_aws_service_list:
  - ecs-tasks.amazonaws.com
  - application-autoscaling.amazonaws.com
  - ec2.amazonaws.com
  - ecs.amazonaws.com
  - codebuild.amazonaws.com
  - codedeploy.amazonaws.com
  - codepipeline.amazonaws.com
  - eks.amazonaws.com

#NEEDED?
app_roles: 
  - raffle_backend_service_role
  - identity_oauth2_service_role

##Definition for general roles
infra_core_roles:
  EksClustersServiceRole:
    managed_policies_arn:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    assume_role_policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - eks.amazonaws.com
          Action:
            - sts:AssumeRole
  EksClustersNodeGroupsServiceRole:
    managed_policies_arn:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::{{AWS_ACCOUNT}}:policy/Route53Editor
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    assume_role_policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - ec2.amazonaws.com
          Action:
            - sts:AssumeRole

##Definition for infra policies
infra_managed_policies:
  Route53Editor:
    policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - route53:ChangeResourceRecordSets
          Resource:
            - arn:aws:route53:::hostedzone/*
        - Effect: Allow
          Action:
            - route53:ListHostedZones
            - route53:ListResourceRecordSets
            - route53:ListTagsForResource
          Resource:
            - "*"
  CodeStartConnections_Policy:
    policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - codestar-connections:CreateConnection
            - codestar-connections:DeleteConnection
            - codestar-connections:UseConnection
            - codestar-connections:GetConnection
            - codestar-connections:ListConnections
            - codestar-connections:TagResource
            - codestar-connections:ListTagsForResource
            - codestar-connections:UntagResource
          Resource:
            - "*"

#Definitions for App specific roles
app_service_roles_managed_policies:
  ApplicationServiceRolesManagedPolicy:
    policy:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - sts:AssumeRole
          Resource:
            - "*"
        - Action:
            - ssm:GetParameter
            - ssm:PutParameter
            - ssm:GetParameters
            - ssm:DeleteParameter
            - ssm:GetParametersByPath
            - ssm:DescribeParameters
          Effect: Allow
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:GetRepositoryPolicy
            - ecr:DescribeRepositories
            - ecr:ListImages
            - ecr:DescribeImages
            - ecr:BatchGetImage
            - ecr:GetLifecyclePolicy
            - ecr:GetLifecyclePolicyPreview
            - ecr:ListTagsForResource
            - ecr:DescribeImageScanFindings
            - ecr:CompleteLayerUpload
            - ecr:GetAuthorizationToken
            - ecr:UploadLayerPart
            - ecr:InitiateLayerUpload
            - ecr:BatchCheckLayerAvailability
            - ecr:PutImage
            - ecr:CreateRepository
          Resource:
            - "*"
        - Effect: Allow
          Resource:
            - "*"
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeDhcpOptions
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            - ec2:DescribeSubnets
            - ec2:DescribeSecurityGroups
            - ec2:DescribeVpcs
            - ec2:CreateNetworkInterfacePermission
          Resource:
            - "*"
        - Effect: Allow
          Resource:
            - "*"
          Action:
            - codecommit:GitPull
            - codecommit:GetBranch
            - codecommit:GetCommit
            - codecommit:UploadArchive
            - codecommit:GetUploadArchiveStatus
            - codecommit:CancelUploadArchive
        - Effect: Allow
          Resource:
            - "*"
          Action:
            - s3:Get*
            - s3:List*
            - s3:PutObject
            - s3:GetBucketAcl
            - s3:GetBucketLocation
        - Effect: Allow
          Action:
            - codebuild:CreateReportGroup
            - codebuild:CreateReport
            - codebuild:UpdateReport
            - codebuild:BatchPutTestCases
            - codebuild:BatchPutCodeCoverages
            - codebuild:CreateProject
            - codebuild:StartBuild
            - codebuild:BatchGetBuilds
          Resource:
            - "*"
        - Action:
            - sqs:GetQueueAttributes
            - sqs:GetQueueUrl
            - sqs:ListDeadLetterSourceQueues
            - sqs:ListQueues
            - sqs:SendMessage
            - sqs:ReceiveMessage
          Effect: Allow
          Resource:
            - "*"
        - Action:
            - codestar-connections:CreateConnection
            - codestar-connections:DeleteConnection
            - codestar-connections:UseConnection
            - codestar-connections:GetConnection
            - codestar-connections:ListConnections
            - codestar-connections:TagResource
            - codestar-connections:ListTagsForResource
            - codestar-connections:UntagResource
          Effect: Allow
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - eks:ListNodegroups
            - eks:DescribeFargateProfile
            - eks:UntagResource
            - eks:ListTagsForResource
            - eks:DescribeAddon
            - eks:CreateFargateProfile
            - eks:DescribeNodegroup
            - eks:DescribeIdentityProviderConfig
            - eks:ListUpdates
            - eks:DescribeUpdate
            - eks:TagResource
            - eks:AccessKubernetesApi
            - eks:CreateAccessEntry
            - eks:DescribeCluster
            - eks:ListClusters
            - eks:ListIdentityProviderConfigs
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - route53:ChangeResourceRecordSets
          Resource:
            - arn:aws:route53:::hostedzone/*
        - Effect: Allow
          Action:
            - route53:ListHostedZones
            - route53:ListResourceRecordSets
            - route53:ListTagsForResource
          Resource:
            - "*"
