---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ name }}
    app.kubernetes.io/part-of: {{ namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{#if cert_manager}}
    cert-manager.io/cluster-issuer: "{{ target }}-{{ cert_manager_name }}"
    {{/if}}
    {{#if limit_rps}}
    nginx.ingress.kubernetes.io/limit-rps: "{{ limit_rps }}"
    {{/if}}
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  {{#if ssl_secret }}
  tls:
    - hosts:
      - {{ name }}.{{ domain }}
      secretName: {{ name }}-tls
  {{/if }}
  rules:
    - host: {{ name }}.{{ domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ name }}
              port:
                number: {{ port }}
    