---
apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
{{#if apply_label}}
  labels:
      app: {{ name }}
{{/if}}
spec:
  ports:
  - name: web
    port: {{ port }}
    protocol: TCP
    targetPort: {{ port }}
  selector:
    app: {{ name }}
  sessionAffinity: None
  type: ClusterIP
